### ISSUE TITLE
Highlighted text is unreadable in the search box

### ISSUE THREAD

**Issue by pmnord** [freeCodeCamp/freecodecamp-dark-vscode-theme#3]
![image](https://user-images.githubusercontent.com/14935197/133795188-5df6fbcb-2151-41b0-a669-ec0ee3513e49.png)

**Comment by shyeon0111** [comment]
The cause of this symptom is `selection.background` property.

As a result, I temporarily rolled back as below.

* Add `setting.json`
`"workbench.colorCustomizations": {
        "selection.background": "#264f78",
      }`

**Comment by moT01** [comment]
Thanks for catching this and the fix @pmnord & @shyeon0111 - it should be live as soon as the marketplace updates the extension
